name: extended_text
description: Extended official text to build special text like inline image or @somebody quickly,it also support custom background,custom over flow and custom selection toolbar and handles.
version: 7.0.0
homepage: https://github.com/fluttercandies/extended_text
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  extended_text_library:
    git:
      url: https://github.com/shuihuadx/extended_text_library.git # Repo
      # ref: master # Branch name
      # 使用分支名存在缺陷,当远端代码更新后,此处没有立即更新,所以这里直接依赖某次提交
      ref: bf2dbf5751076c3181b593c58fbe032c858a4244
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


